version: 2.1
orbs:
  python: circleci/python@1.2

executors:
  my-executor:
    docker:
      - image: cimg/python:3.10
    environment:
      TZ: "Australia/Melbourne"
      
jobs:
  build-and-test:
    executor: my-executor
    steps:
      - checkout
      - run: 
          name: "Install packages"
          command: | 
              sudo apt update -y 
              sudo apt install -y build-essential libxml2 libxml2-dev zlib1g-dev python3-tk graphviz
      - run:
          name: "Build "
          command: |
              pip install pip==20.0.2
              pip install -e .[default]
      - run:
          name: "Run test"
          command: pytest tests/test.py
          no_output_timeout: 3h
      - run: 
          name: "Reproduce BARO performance on the Online Boutique dataset"
          command: python rq2.py --method baro --dataset online-boutique

workflows:
  main-flow:
    jobs:
      - build-and-test
  build-daily:
    triggers:
      - schedule:
          cron: "49 15 * * *"
          filters:
            branches:
              only: main
    jobs:
      - build-and-test
